name: Aktualizacja danych

on:
  schedule:
    - cron: '0 6 * * *'  # codziennie o 6:00 UTC
  workflow_dispatch:     # umożliwia ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (optional)
      run: pip install -r requirements.txt || true

    - name: Run script
      run: python update.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data.json
        git commit -m "Aktualizacja danych" || echo "Brak zmian"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
